config/routes.rb
Rails.application.routes.draw do

  resources :add_impressions_count_to_products
  post 'admins/products/new' => 'admins_products#create'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :endusers, controllers: {
    sessions: 'endusers/sessions',
    passwords: 'endusers/passwords',
    registrations: 'endusers/registrations'
  }

  root 'products#index'
  resources :endusers , only: [:edit, :show, :update, :destroy] 
  resources :product_carts , only: [:index, :create, :destroy, :update]  
  resources :orders , only: [:new, :index, :create, :destroy]
  resources :order_details , only: [:create, :destroy]
  resources :contacts , only: [:index, :new, :create]
  resources :user_addresses
  resources :artists, only: [:index, :create, :destroy]
  resources :labels, only: [:index, :create, :destroy]
  resources :genres, only: [:index, :create, :destroy]
  resources :products, only: [:index, :show,:new]do
    resource :favorites, only: [:create, :destroy]
  end

  namespace :admins do
  resources :products , only: [:new, :create, :index, :edit, :update, :destroy, :show]
  resources :endusers , only: [:index, :show, :edit, :update, :destroy]
  resources :orders , only: [:index, :update]  
  resources :contacts , only: [:index, :show, :create] 
  resources :homes , only: [:index] 
  end
end

app/models/enduser.rb
class Enduser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :product_carts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :products, through: :favorites
  has_many :user_addresses, dependent: :destroy
  validates :first_name, presence: true
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :family_name, presence: true
  validates :family_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true
  validates :registration_address, presence: true
  validates :registration_postal_code, presence: true, format: { with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}\z/ }
  validates :phone_number, presence: true
end

app/controllers/admins/endusers_controller.rb
class Admins::EndusersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @endusers = Enduser.all
  end

  def show
    @enduser = Enduser.find(params[:id])

    @history = Order.order("created_at DESC")
    @history = Order.where(enduser_id: @enduser.id )


  end

  def edit
    @enduser = Enduser.find(params[:id])
  end

  def update
    @enduser = Enduser.find(params[:id])
    if @enduser.update(enduser_params)
      redirect_to admins_endusers_path
    else
      render action: "edit"
    end
  end

  private

  def enduser_params
    params.require(:enduser).permit(:first_name, :first_name_kana, :family_name, :family_name_kana, :registration_address, :registration_postal_code, :phone_number, :email)
  end
end

app/controllers/endusers/confirmations_controller.rb
# frozen_string_literal: true

class Endusers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/endusers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Endusers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/endusers/passwords_controller.rb
# frozen_string_literal: true

class Endusers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/endusers/registrations_controller.rb
# frozen_string_literal: true

class Endusers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/endusers/sessions_controller.rb
# frozen_string_literal: true

class Endusers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/endusers/unlocks_controller.rb
# frozen_string_literal: true

class Endusers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/endusers_controller.rb
class EndusersController < ApplicationController
  protect_from_forgery
  before_action :authenticate_enduser!
  before_action :correct_enduser, only: [:edit, :show, :update]

  def edit
    @enduser = Enduser.find(params[:id])
  end

  def show
    @favorites = Favorite.where(enduser_id: @current_enduser.id)
    # @product = Product.find_by(id: favorites.product_id)
    
    @history = Order.where(enduser_id: @current_enduser.id )
    @history = Order.order("created_at DESC")

  end

  def like(product)
    favorites.find_or_create_by(product_id: product.id)
  end

  def unlike(product)
    favorite = favorites.find_by(product_id: product.id)
    favorite.destroy if favorite
  end

  def orders
    @order = OrderDetail.find(paramas[:id])
  end

  def new
    @enduser = Enduser.new
  end

  def destroy
    enduser = Enduser.find(params[:id])
    enduser.destroy
    redirect_to products_path
  end

  def update
    @enduser = Enduser.find(params[:id])
    if @enduser.update(enduser_params)
      redirect_to enduser_path(@enduser.id), notice: "プロフィールを変更しました"
    else
      render action: "edit"
    end
  end

  private

  def enduser_params
    params.require(:enduser).permit(:first_name, :first_name_kana, :family_name, :family_name_kana, :registration_address, :registration_postal_code, :phone_number, :email)
  end

  def correct_enduser
    enduser = Enduser.find(params[:id])
    if current_enduser != enduser
      redirect_to new_enduser_registration_path
    end
  end
end

app/helpers/admins/endusers_helper.rb
module Admins::EndusersHelper
end

app/views/admins/endusers/edit.html.erb
<%= render "endusers/admin" %>
<div id="wrapper">
  <section class="slice slice-lg sct-color-1">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 " >
              <div class="form-user style-1">

                  <div class="form-header text-center">
                     <h2>会員情報編集</h2>
                  </div>
                  <div class="form-body">
                      <%= form_for(@enduser , url:{controller: "endusers", action: "update"}) do |f| %>
                        <%= render "devise/shared/error_messages", resource: resource %>

                      <div class="col-lg-5 col-md-5">
                        <div class="form-group">
                          <div class="field">
                            <%= f.label "姓" %><br />
                            <%= f.text_field :family_name, autofocus: true, class:"form-control " , id:"family_name", placeholder:"姓" %>
                          </div>
                        </div>
                      </div>

                      <div class="col-lg-5 col-lg-offset-2 col-md-5 col-md-offset-2">
                        <div class="form-group">
                          <div class="field">
                            <%= f.label "名" %><br />
                            <%= f.text_field :first_name, autofocus: true,class:"form-control ", id:"first_name" , placeholder:"名" %>
                          </div>
                        </div>
                      </div>

                      <div class="col-lg-5 col-md-5">
                        <div class="form-group">
                          <div class="field">
                            <%= f.label "フリガナ(セイ)" %><br />
                            <%= f.text_field :family_name_kana, autofocus: true,class:"form-control", id:"family_name_kana", placeholder:"フリガナ(セイ)"%>
                          </div>
                        </div>
                      </div>
                      <div class="col-lg-5 col-lg-offset-2 col-md-5 col-md-offset-2">
                        <div class= "form-group">
                          <div class="field ">
                            <%= f.label "フリガナ(メイ)" %><br />
                            <%= f.text_field :first_name_kana, autofocus: true,class:"form-control" , id:"first_name_kana", placeholder:"フリガナ(メイ)" %>
                          </div>
                        </div>
                      </div>

                      <div class="col-lg-12">
                        <div class="form-group">
                            <div class="field">
                              <%= f.label :住所  %><font size="1">*ハイフンあり</font><br />
                              <%= f.text_field :registration_address, autofocus: true, autocomplete: "registration_address" ,class:"form-control", id:"registration_address",placeholder:"住所" %>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="field">
                              <%= f.label :郵便番号%><font size="1">*ハイフンあり半角英数</font><br />
                              <%= f.text_field :registration_postal_code, autofocus: true, autocomplete: "registration_postal_code",class:"form-control",id:"registration_postal_code", placeholder:"郵便番号" %>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="field">
                              <%= f.label :電話番号%><font size="1">*ハイフンあり半角英数</font><br />
                              <%= f.text_field :phone_number, autofocus: true, autocomplete: "phone_number",class:"form-control",id:"phone_number",placeholder:"電話番号" %>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="field">
                              <%= f.label :メールアドレス %><br />
                              <%= f.email_field :email, autofocus: true, autocomplete: "email",class:"form-control", id:"email",placeholder:"メールアドレス" %>
                            </div>
                        </div>


                      </div>

                        <div class="actions">
                          <div style="padding: 6px, 12px; font-size: 20px; margin: 20px 15px 0 15px; ">
                            <%= f.submit "変更を保存" , class: "btn btn-block btn-warning "  %>
                          </div>
                        </div>
                      </div>
                      <% end %>
                      <div class ="actions">
                          <div style="padding: 6px, 12px; font-size: 20px; margin: 20px 15px 0 15px; ">
                            <%= button_to "アカウント削除" ,registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete ,  class: "btn btn-block btn-danger " %>
                          </div>
                        </div>
                  </div>
                </div>
              </div>

</section>
</div>

app/views/admins/endusers/index.html.erb
<%= render "endusers/admin" %>
<div id="wrapper">
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<div style="border: 2px solid #8C8C00;">
				<table class="table" style="width: 100%;">
					<thead>
						<tr>
							<th class="col-lg-1 col-md-1">ID</th>
							<th class="col-lg-4 col-md-4">姓</th>
							<th class="col-lg-4 col-md-4">名</th>
							<th class="col-lg-1 col-md-1">編集</th>
							<th class="col-lg-2 col-md-2">削除</th>
						</tr>
					</thead>
					<tbody>
						<% @endusers.each do |u| %>
						<tr>
							<td class="col-lg-1 col-md-1"><%= link_to u.id , admins_enduser_path(u) %></td>
							<td class="col-lg-4 col-md-4"><%= link_to u.family_name , admins_enduser_path(u) %></td>
							<td class="col-lg-4 col-md-4"><%= link_to u.first_name , admins_enduser_path(u) %></td>
							<td class="col-lg-1 col-md-1"><%= link_to "編集", edit_admins_enduser_path(u) , class: "btn btn-warning"%></td>
							<td class="col-lg-2 col-md-2">
								<%= button_to "アカウント削除", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete , class: "btn btn-danger"%>
							</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
</div>

app/views/admins/endusers/show.html.erb
<%= render "endusers/admin" %>
<div id="wrapper">
<div class=body>
	<div class=container>
		<div class ="col-md-6 col-md-offset-3 user-info-form ">
			<div class = "row" >
				<div class="form-user style-2">
					<h2 style="text-align: center;">会員情報</h2>
					<table class="table" >
						<tbody>
							<tr>
								<th>Name</th>
								<th><%= "#{@enduser.family_name}" + " " + "#{@enduser.first_name}" %></th>
							</tr>
							<tr>
								<th>Name(フリガナ)</th>
								<th><%= "#{@enduser.family_name_kana}" + " " + "#{@enduser.first_name_kana}" %></th>
							</tr>
							<tr>
								<th>住所</th>
								<th><%= "#{@enduser.registration_address}" %></th>
							</tr>
							<tr>
								<th>郵便番号</th>
								<th><%= "#{@enduser.registration_postal_code}" %></th>
							</tr>
							<tr>
								<th>電話番号</th>
								<th><%= "#{@enduser.phone_number}" %></th>
							</tr>
							<tr>
								<th>メールアドレス</th>
								<th><%= "#{@enduser.email}" %></th>
							</tr>
						</tbody>
					</table>
            		<%= link_to edit_admins_enduser_path , class: "col-xs-12 btn btn-warning glyphicon glyphicon-wrench edit_enduser_#{}" do %>
          			<% end %>
				</div>
			</div>
		</div>
		<div class ="col-lg-10 col-md-10 col-lg-offset-1 col-md-offset-1">
			<h2>購入履歴</h2>
			<div class="row">
				<ul >
		          <% @history.each do |h| %>
		          <div class="product-cart">
							<table>
								<tbody>
									<tr>
										<td class="product-cart-index">
											宛名:<%=  h.ship_name %>
										</td>
										<td class="product-cart-index">
											宛先:<%= h.ship_address %>
										</td>
										<td class="product-cart-index">
											¥
											<%= h.purchase_amount %>
										</td>
										<td class="product-cart-index">
											注文日:<%= h.created_at.strftime("%Y-%m-%d") %>
										</td>
									</tr>
								</tbody>
							</table>
							<% h.order_details.each do |d| %>
								<div class ="order-detail">
									<table>
										<tbody>
											<tr>
												<td class ="product-cart-index">
													<%= link_to product_path(d.product.id)do %>
													<%= attachment_image_tag d.product, :jacket, size: "140x140" , fallback: "l_e_others_500.jpg" %>
													<% end %>
												</td>
												<td class="product-cart-index">　</td>
												<td class="product-cart-index">
													<p>Teitle：</p>
													<p>購入枚数：</p>
													<p>小計：</p>
												</td>
												<td class="product-cart-index">
													<P><%= link_to d.product.product_name , product_path(d.product.id) %></P>
													<p><%= d.purchase_qty %></p>
													<p><%= d.purchase_price %></p>
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							<% end %>
						</div>
		          <% end %>
		        </ul>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-offset-10 col-lg-2">
				<div>
					<%= link_to "戻る", :back %>
				</div>
			</div>
		</div>
	</div>
</div>
</div>