config/routes.rb
Rails.application.routes.draw do

  resources :add_impressions_count_to_products
  post 'admins/products/new' => 'admins_products#create'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :endusers, controllers: {
    sessions: 'endusers/sessions',
    passwords: 'endusers/passwords',
    registrations: 'endusers/registrations'
  }

  root 'products#index'
  resources :endusers , only: [:edit, :show, :update, :destroy] 
  resources :product_carts , only: [:index, :create, :destroy, :update]  
  resources :orders , only: [:new, :index, :create, :destroy]
  resources :order_details , only: [:create, :destroy]
  resources :contacts , only: [:index, :new, :create]
  resources :user_addresses
  resources :artists, only: [:index, :create, :destroy]
  resources :labels, only: [:index, :create, :destroy]
  resources :genres, only: [:index, :create, :destroy]
  resources :products, only: [:index, :show,:new]do
    resource :favorites, only: [:create, :destroy]
  end

  namespace :admins do
  resources :products , only: [:new, :create, :index, :edit, :update, :destroy, :show]
  resources :endusers , only: [:index, :show, :edit, :update, :destroy]
  resources :orders , only: [:index, :update]  
  resources :contacts , only: [:index, :show, :create] 
  resources :homes , only: [:index] 
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contact_answers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.search(search)
    if search
      Product.where(['product LIKE ?'], "%#{search}%")
    else
      Producd.all
    end
  end
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  validates :artist_name, presence: true, uniqueness: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :contact_answers, inverse_of: :contact
  belongs_to :enduser

  accepts_nested_attributes_for :contact_answers, reject_if: :all_blank, allow_destroy: true

  enum status: [:未返信, :返信済み]
end

app/models/contact_answer.rb
class ContactAnswer < ApplicationRecord
  belongs_to :contact
  belongs_to :admin
end

app/models/disk.rb
class Disk < ApplicationRecord
  belongs_to :product
  has_many :songs, inverse_of: :disk
  accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true
end

app/models/enduser.rb
class Enduser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :product_carts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :products, through: :favorites
  has_many :user_addresses, dependent: :destroy
  validates :first_name, presence: true
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :family_name, presence: true
  validates :family_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true
  validates :registration_address, presence: true
  validates :registration_postal_code, presence: true, format: { with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}\z/ }
  validates :phone_number, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :enduser
  belongs_to :product
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :songs, dependent: :destroy
  validates :genre_name, presence: true, uniqueness: true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :label_name, presence: true, uniqueness: true
end

app/models/lebel.rb
class Lebel < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :enduser
  enum payment: [:銀行振込, :クレジット, :代引き]
  enum order_status: [:受付中, :商品準備中, :出荷済]
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def total_price
    product.price * product_count
  end
end

app/models/product.rb
class Product < ApplicationRecord

  acts_as_paranoid
 
  is_impressionable counter_cache: true


  has_many :favorites, dependent: :destroy
  has_many :product_carts, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :disks, inverse_of: :product

  has_many :songs, through: :disks
  has_many :enduser, through: :favorites

  accepts_nested_attributes_for :disks, reject_if: :all_blank, allow_destroy: true
  belongs_to :label

  attachment :jacket

  def favorited_by?(enduser)
    favorites.where(enduser_id: enduser.id).exists?
  end
end

app/models/product_cart.rb
class ProductCart < ApplicationRecord
  belongs_to :enduser
  belongs_to :product
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :disk
  belongs_to :artist
  belongs_to :genre
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :enduser
end

app/controllers/admins/contacts_controller.rb
class Admins::ContactsController < ApplicationController
  def index
    @contact = Contact.all
    @contact = Contact.order("created_at DESC")
  end

  def show
    @contact = Contact.find(params[:id])
    @contact_answers = ContactAnswer.new
  end

  def create
    @contact_answers = ContactAnswer.new(contact_answers_params)
    @contact = Contact.find(params[:contact_id])
    @contact_answers.contact_id = @contact.id
    @contact_answers.admin_id = current_admin.id
    @contact_answers.save
    @contact.update(status: 1)


    ContactMailer.thanks_email(@contact_answers, params[:contact_id]).deliver
    redirect_to admins_homes_path
  end

  private

  def contact_answers_params
    params.require(:contact_answer).permit(:answer_title, :answer_message, :contact_status, )
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.enduser_id = current_enduser.id
    @contact.save

    ContactMailer.received_email(@contact).deliver
    render :action => 'create'
  end

  private

  def contact_params
    params.require(:contact).permit(:contact_message, :name, :contact_title, :status)
  end
end

app/helpers/admins/contacts_helper.rb
module Admins::ContactsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/contacts/index.html.erb
<%= render "endusers/admin" %>
<div class="container">
	<div class="row">
		<div class="col-md-12">
            <table class="table table-border">
	            <thead>
		            <tr>
			            <th>名前</th>
			            <th>title</th>
			            <th>問い合わせ内容</th>
			            <th>返信内容</th>
			            <th>emailaddres</th>
		            </tr>
	            </thead>
            <% @contact.each do |contact| %>
                <tbody>
	                <tr>
		                <th><%= link_to contact.name, admins_enduser_path(contact.enduser.id) %></th>
		                <th><%= link_to contact.contact_title, admins_contact_path(contact.id) %></th>
		                <th><%= contact.contact_message %></th>
		                <% if ContactAnswer.exists?(contact_id: contact.id) %>
			                <% if contact.contact_answers.last.answer_message.blank? %>
			                	<th></th>
			                <% else %>
			            	    <th><%= contact.contact_answers.last.answer_message %></th>
			                <% end %>
		                <% else %>
		                	<th></th>
		                <% end %>

		                <th><%= contact.enduser.email %></th>
	                </tr>
                </tbody>
            <% end %>
            </table>
        </div>
    </div>
</div>

app/views/admins/contacts/show.html.erb
<%= render "endusers/admin" %>
<div class="container">
  <div class="row">
  	<div class="contact col-md-6 col-md-offset-3">
      <div class="panel panel-default bg-danger">
      <div class="panel-heading">回答状況</div>
      <div class="panel-body"><%= @contact.status %></div>
      <div class="panel-heading">名前</div>
      <div class="panel-body"><%= @contact.name %></div>
      <div class="panel-heading">日時</div>
      <div class="panel-body"><%= @contact.created_at.strftime('%Y/%m/%d %H:%M') %></div>
      <div class="panel-heading">メールアドレス</div>
      <div class="panel-body"><%= @contact.enduser.email %></div>
      <div class="panel-heading">タイトル</div>
      <div class="panel-body"><%= @contact.contact_title %></div>
      <div class="panel-heading">お問い合わせ内容</div>
      <div class="panel-body"><%= @contact.contact_message %></div>
    </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="contact col-md-6 col-md-offset-3">

      <div class="form-group">
    <%= form_for(@contact_answers, url: admins_contacts_path(contact_id: @contact.id)) do |f| %>
　　　<div class="page-header">

      <h1>返信フォーム</h1>
     </div>

    <tr>
      <th>タイトル</th>
      <div class="form-group"><%= f.text_field :answer_title, class:'form-control'%></div>
    </tr>

    <tr>
      <th>お問い合わせ内容</th>
      <div class="form-group"><%= f.text_area :answer_message,class:'form-control'%></div>
    <%= f.submit '送信', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>
</div>
</div>
  </div>