config/routes.rb
Rails.application.routes.draw do

  resources :add_impressions_count_to_products
  post 'admins/products/new' => 'admins_products#create'
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :endusers, controllers: {
    sessions: 'endusers/sessions',
    passwords: 'endusers/passwords',
    registrations: 'endusers/registrations'
  }

  root 'products#index'
  resources :endusers , only: [:edit, :show, :update, :destroy] 
  resources :product_carts , only: [:index, :create, :destroy, :update]  
  resources :orders , only: [:new, :index, :create, :destroy]
  resources :order_details , only: [:create, :destroy]
  resources :contacts , only: [:index, :new, :create]
  resources :user_addresses
  resources :artists, only: [:index, :create, :destroy]
  resources :labels, only: [:index, :create, :destroy]
  resources :genres, only: [:index, :create, :destroy]
  resources :products, only: [:index, :show,:new]do
    resource :favorites, only: [:create, :destroy]
  end

  namespace :admins do
  resources :products , only: [:new, :create, :index, :edit, :update, :destroy, :show]
  resources :endusers , only: [:index, :show, :edit, :update, :destroy]
  resources :orders , only: [:index, :update]  
  resources :contacts , only: [:index, :show, :create] 
  resources :homes , only: [:index] 
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contact_answers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.search(search)
    if search
      Product.where(['product LIKE ?'], "%#{search}%")
    else
      Producd.all
    end
  end
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  validates :artist_name, presence: true, uniqueness: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :contact_answers, inverse_of: :contact
  belongs_to :enduser

  accepts_nested_attributes_for :contact_answers, reject_if: :all_blank, allow_destroy: true

  enum status: [:未返信, :返信済み]
end

app/models/contact_answer.rb
class ContactAnswer < ApplicationRecord
  belongs_to :contact
  belongs_to :admin
end

app/models/disk.rb
class Disk < ApplicationRecord
  belongs_to :product
  has_many :songs, inverse_of: :disk
  accepts_nested_attributes_for :songs, reject_if: :all_blank, allow_destroy: true
end

app/models/enduser.rb
class Enduser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  acts_as_paranoid
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :product_carts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :products, through: :favorites
  has_many :user_addresses, dependent: :destroy
  validates :first_name, presence: true
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :family_name, presence: true
  validates :family_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :email, presence: true
  validates :registration_address, presence: true
  validates :registration_postal_code, presence: true, format: { with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}\z/ }
  validates :phone_number, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :enduser
  belongs_to :product
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :songs, dependent: :destroy
  validates :genre_name, presence: true, uniqueness: true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :label_name, presence: true, uniqueness: true
end

app/models/lebel.rb
class Lebel < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :enduser
  enum payment: [:銀行振込, :クレジット, :代引き]
  enum order_status: [:受付中, :商品準備中, :出荷済]
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def total_price
    product.price * product_count
  end
end

app/models/product.rb
class Product < ApplicationRecord

  acts_as_paranoid
 
  is_impressionable counter_cache: true


  has_many :favorites, dependent: :destroy
  has_many :product_carts, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :disks, inverse_of: :product

  has_many :songs, through: :disks
  has_many :enduser, through: :favorites

  accepts_nested_attributes_for :disks, reject_if: :all_blank, allow_destroy: true
  belongs_to :label

  attachment :jacket

  def favorited_by?(enduser)
    favorites.where(enduser_id: enduser.id).exists?
  end
end

app/models/product_cart.rb
class ProductCart < ApplicationRecord
  belongs_to :enduser
  belongs_to :product
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :disk
  belongs_to :artist
  belongs_to :genre
end

app/models/user_address.rb
class UserAddress < ApplicationRecord
  belongs_to :enduser
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @product = Product.new
    @disk = @product.disks.build
    @song = @disk.songs.build
  end

  def create
    @product = Product.new(product_params)

    @product.save
    redirect_to admins_products_path
  end

  def index
    @products = Product.all
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
    @disks = @product.disks
    @price = (@product.price * 1.08).floor
    impressionist(@product, nil, :unique => [:session_hash])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:success] = "商品情報を更新しました。"
      redirect_to admins_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:info] = "商品を削除しました。"
    redirect_to admins_products_path
  end

  private

  def product_params
    params.require(:product).permit(:jacket, :product_name, :label_id, :product_stock, :product_status, :price,
                                    disks_attributes: [:id, :product_id, :disk_name, :_destroy,
                                                       songs_attributes: [:id, :disk_id, :artist_id, :genre_id, :song_name, :number, :_destroy]])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @product = Product.new
    @disk = @product.disks.build
    @song = @disk.songs.build
  end

  def create
    @product = Product.new(product_params)

    @product.save
    redirect_to admins_products_path
  end

  def index
    @products = Product.all
    @all_ranks = Product.find(Favorite.group(:product_id).order('count(product_id) desc').limit(5).pluck(:product_id))
    @most_viewed = Product.order('impressions_count DESC').take(5)
  end

  def show
    @product = Product.find(params[:id])
    @cart = ProductCart.new
    @disks = @product.disks
    @price = (@product.price * 1.08).floor

    @count = @product.product_stock - 0
    impressionist(@product, nil, :unique => [:session_hash])
  
    # @carts = ProductCart.where(enduser_id: current_enduser.id)
    # if @carts.product_ids.include?(@product.id)
    # @carts.each do |cart|
    #     if cart.product_id == @product.product_id
    #     count =  @product.product_count - cart.product_count
    #     @count = count

    # end

    # end

    # end
    # end
  end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<%= render "endusers/header" %>
<div id="wrapper">
  <div class="bg-1"></div>

  <div class="bg-1">
    <div style="padding-top: 50px;">
          <ul class ="bxslider-3" style="width: 100%;">

            <% @products.each do |j| %>
              <li>
              <%= link_to product_path(j.id) do %>
                  <%= attachment_image_tag j, :jacket, size: "100x100" , fallback: "l_e_others_500.jpg" %>
              <% end %>
              </li>
            <% end %>
          </ul>
    </div>
      <div class="bxslider1">
        <div id="slider-wrapper">
        <div id="slider-inner">
          <ul class ="bxslider">
            <% @products.each do |j| %>
              <li>
              <%= link_to product_path(j.id) do %>
                  <%= attachment_image_tag j, :jacket, size: "350x350" , fallback: "l_e_others_500.jpg" %>
              <% end %>
              </li>
            <% end %>
          </ul>
        </div>
        </div>
          <ul class ="bxslider-2" style="width: 100%;">
            <% @products.each do |j| %>
              <li>
              <%= link_to product_path(j.id) do %>
                  <%= attachment_image_tag j, :jacket, size: "100x100" , fallback: "l_e_others_500.jpg" %>
              <% end %>
              </li>
            <% end %>
            </li>
        </ul>
      </div>

    </div>





<div class="container">
  <div class = "row">

    <div class = "col-lg-2">
      <h2>商品一覧</h2>
      <label>いいね数ランキング</label>
      <% @all_ranks.each.with_index(1) do |r, i| %>
        <h4>
          <%= "第#{i}位" %>
          <%= link_to product_path(r.id) do %>
                  <%= attachment_image_tag r, :jacket, size: "140x140" , fallback: "l_e_others_500.jpg" %>
                <% end %>
            <%= link_to r.product_name , product_path(r.id) %>
             <P><i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                <%= r.favorites.count  %></P>
        </h4>
      <% end %>
          <label style="padding-top: 90px;">PV数ランキング</label>
          <% @most_viewed.each.with_index(1) do |rank, i| %>
            <h4>
              <td><%= "#{i}位" %></td>
              <%= link_to product_path(rank.id) do %>
                  <%= attachment_image_tag rank, :jacket, size: "140x140" , fallback: "l_e_others_500.jpg" %>
                <% end %>
              <%= link_to rank.product_name , product_path(rank.id) %>
              <% if rank.impressions_count.blank? %>
              <p>0pv</p>
              <% else %>
              <p><%= rank.impressions_count %>pv</p>             
              <% end %>
            </h4>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class = "col-lg-10">
      <div class = "row">
        <% @search_products.each do |product| %>
          <div class = "col-lg-2 col-lg-offset-2">
            <th>
              <div>
                <%= link_to product_path(product.id) do %>
                  <%= attachment_image_tag product, :jacket, size: "240x240" , fallback: "l_e_others_500.jpg" %>
                <% end %>
              </div>
              <div><%= link_to product.product_name, product_path(product.id) %>
                <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                <%= product.favorites.count  %>
              </div>
              <div><%= product.disks.first.songs.first.artist.artist_name %></div>
              <% if product.product_status == "販売中" %>
                <div>￥<%= product.price %>円(税込)</div>
              <% else %>
                <div><%= product.product_status %></div>
              <% end %>
            </th>
          </div>

        <% end %>
      </div>

      <p id="page-top"><a href="#">PAGE TOP</a></p>

    </div>
  </div>
</div>

app/views/products/show.html.erb
<%= render "endusers/header" %>
<div id="wrapper">
<div class="container">
  
  <h2>商品詳細</h2>
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
        <%= attachment_image_tag @product, :jacket, size: "300x300" , fallback: "l_e_others_500.jpg" %>
      </div>
      <div class="col-md-6">
        <label>商品名：<%= @product.product_name %></label>
        <p><div class="product-artist">アーティスト：<%= @product.disks.first.songs.first.artist.artist_name %></div></p>
        <p>レーベル：<%= @product.label.label_name %></p>
        <p>ジャンル：<%= @product.disks.first.songs.first.genre.genre_name %></p>
        <% if @product.product_status == "販売中" %>
          <p>価格(税込)：￥<%= @price %>円</p>
        <% else %>
          <p><%= @product.product_status %></p>
        <% end %>
        <% if @product.product_status == "販売中" %>
          <th>在庫：</th>
            <% if @product.product_stock == 0 %>
              <th>無</th>
            <% else %>
              <th>有</th>
            <% end %>
        <% end %>

        <% if enduser = signed_in? %>
          <h4>収録曲</h4>
            <% @disks.each do |disk| %>
              <p><label>ディスク名：</label><%= disk.disk_name %></p>
              <ul class="song-list">
                <% disk.songs.each do |song| %>
                  <p>No<%= song.number %>．<%= song.song_name %></p>
                <% end %>
              </ul>
            <% end %>

            <% if @product.favorited_by?(current_enduser) %>
              <p>
                <%= link_to product_favorites_path(@product), method: :delete do %>
                  <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                  いいね
                <% end %>
              </p>
            <% else %>
              <p>
                <%= link_to product_favorites_path(@product), method: :post do %>
                  <i class="far fa-heart" aria-hidden="true" style="color: black;" ></i>
                  いいね
                <% end %>
              </p>
            <% end %>
        <% else %>
          <h4>収録曲</h4>
            <% @disks.each do |disk| %>
              <p><label>ディスク名：</label><%= disk.disk_name %></p>
              <ul class="song-list">
                <% disk.songs.each do |song| %>
                  <p>No<%= song.number %>．<%= song.song_name %></p>
                <% end %>
              </ul>
            <% end %>
        <% end %>

        <div div class="col-md-6">
          <%= form_for(@cart, url: product_carts_path, method: 'Post') do |f| %>
          <% if @product.product_status == "販売中" %>
          <p><%= f.number_field :product_count,start:1, min:1,max:@product.product_stock, step:1 %>個</p>
          <% end %>
          <%= f.hidden_field :product_id, value: @product.id %>
        </div>
      </div>
    </div>
</div>
<div class="container">
  <div class="col-md-3 col-md-offset-2">
    <%= link_to "商品一覧へ", products_path, class: "btn btn-default btn-lg btn-block" %>
  </div>
  <div class="col-md-3 col-md-offset-1">
    <% if @product.product_status == "販売中" %>
      <%= f.submit 'カート追加', class:"btn btn-default btn-lg btn-block" %>
    <% end %>
  </div>
  <% end %>
</div>
</div>